name: advanced_error_handling
description: An example for advanced error handling
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartz: 0.10.0-nullsafety.1
  flutter:
    sdk: flutter
  freezed_annotation:
  rxdart: 0.26.0
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  import_sorter: 4.4.2
  lint: 1.5.3

flutter:
  uses-material-design: true

import_sorter:
  comments: false
